cmake_minimum_required(VERSION 3.8)
project(amp_utils)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(fs_msgs REQUIRED)
# uncomment the following section in order to fill in
# further dependencies manually.
# find_package(<dependency> REQUIRED)

add_executable(pointcloud_rgb
        src/pointcloud_rgb.cpp
)
ament_target_dependencies(pointcloud_rgb rclcpp sensor_msgs fs_msgs)
target_link_libraries(pointcloud_rgb ${OpenCV_LIBS})

install(
        PROGRAMS 
        src/frequency_monitor_node.py
        DESTINATION lib/${PROJECT_NAME}
)


if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # comment the line when a copyright and license is added to all source files
  set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # comment the line when this package is in a git repo and when
  # a copyright and license is added to all source files
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()

install(TARGETS pointcloud_rgb
        DESTINATION lib/${PROJECT_NAME})

install(
        PROGRAMS 
        src/odom_plot_node.py
        src/simulated_gps_error_node.py
        src/simulated_yaw_error_node.py
        DESTINATION lib/${PROJECT_NAME}
)

install(
        PROGRAMS 
        ros2/autonomous_system_status_indicator_node.py
        DESTINATION lib/${PROJECT_NAME}
)

install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})

ament_package()
